# Assignment 6

In [1]:
# Q1 Python program to add two Matrices

# Get Input from User 

# Get the matrix shape from user for both Matrix 1 and Matrix 2
# Since both matrix should be same shape, We can use one input for creating shape of both matrix

row  = int(input("Enter the row size :"))
column = int(input("Enter the column size :"))

# Now create the nested list
print("Enter the values for Matrix1")
# We are going to use list comprehension method
# Matrix 1
Matrix1 = [[int(input()) for i in range(column)] for j in range(row)] 

# For printing the Matrix1 Values in matrix form
print("Matrix1 :")
for i in range(row):
    for j in range(column):
        print(format(Matrix1[i][j],"<3"),end=" ")
    print()

#Matrix 2
print("Enter the values for Matrix2")
Matrix2 = [[int(input()) for i in range(column)] for j in range(row)] 

# For printing the Matrix1 Values in matrix form
print("Matrix2 :")
for i in range(row):
    for j in range(column):
        print(format(Matrix2[i][j],"<3"),end=" ")
    print()

# Calculation

# Create nested list for adding two matrices "Since we need empty nested list keep initial value 0"
result = [[0 for i in range(column)] for j in range(row)] 
# create loop
for i in range(row):
    for j in range(column):
        result[i][j] = Matrix1[i][j] + Matrix2[i][j]

# Output

# Print the final added values of both matrices
print("Added value of two matrices :")
for i in range(row):
    for j in range(column):
        print(format(result[i][j],"<3"),end=" ")
    print()

Enter the row size :2
Enter the column size :2
Enter the values for Matrix1
1
2
3
4
Matrix1 :
1   2   
3   4   
Enter the values for Matrix2
5
6
2
3
Matrix2 :
5   6   
2   3   
Added value of two matrices :
6   8   
5   7   


In [2]:
# Q2 Python program to multiply two matrices

# Get Input from User 

# Get the matrix shape from user for both Matrix 1 and Matrix 2
# Since Matrix 1 column size and matrix 2 row size should be equal, we can get only three inputs
# 1. Row size for M1 2. Column size for M 2 and 3. Common size Col M1/ Row M2

p  = int(input("Enter the row size for M1:"))
q = int(input("Enter the column size for M2:"))
n = int(input("Enter the column size for col_M1/row_M2:"))

# Now create the nested list
print("Enter the values for Matrix1")
# We are going to use list comprehension method
# Matrix 1
Matrix1 = [[int(input()) for i in range(n)] for j in range(p)] 

# For printing the Matrix1 Values in matrix form
print("Matrix1 :")
for i in range(p):
    for j in range(n):
        print(format(Matrix1[i][j],"<5"),end=" ")
    print()

#Matrix 2
print("Enter the values for Matrix2")
Matrix2 = [[int(input()) for i in range(q)] for j in range(n)] 

# For printing the Matrix1 Values in matrix form
print("Matrix2 :")
for i in range(n):
    for j in range(q):
        print(format(Matrix2[i][j],"<5"),end=" ")
    print()

# Calculation

# Create nested list for adding two matrices "Since we need empty nested list keep initial value 0"
result = [[0 for i in range(q)] for j in range(p)] 
# create loop
for i in range(p):
    for j in range(q):
        for k in range(n):
            result[i][j] = result[i][j] + Matrix1[i][k] * Matrix2[k][j]

# Output

# Print the final added values of both matrices
print("Multiplied value of two matrices :")
for i in range(p):
    for j in range(q):
        print(format(result[i][j],"<5"),end=" ")
    print()

Enter the row size for M1:2
Enter the column size for M2:2
Enter the column size for col_M1/row_M2:4
Enter the values for Matrix1
1
4
7
2
5
8
3
6
Matrix1 :
1     4     7     2     
5     8     3     6     
Enter the values for Matrix2
9
6
3
8
5
2
7
4
Matrix2 :
9     6     
3     8     
5     2     
7     4     
Multiplied value of two matrices :
70    60    
126   124   


In [3]:
# Q3 Python program for Matrix Product

# Multiplication using numpy
import numpy as np
# Get Input from User 

# Get the matrix shape from user for both Matrix 1 and Matrix 2
# Since Matrix 1 column size and matrix 2 row size should be equal, we can get only three inputs
# 1. Row size for M1 2. Column size for M 2 and 3. Common size Col M1/ Row M2

p  = int(input("Enter the row size for M1:"))
q = int(input("Enter the column size for M2:"))
n = int(input("Enter the column size for col_M1/row_M2:"))

# Now create the nested list
print("Enter the values for Matrix1")
# We are going to use list comprehension method
# Matrix 1
Matrix1 = [[int(input()) for i in range(n)] for j in range(p)] 

# For printing the Matrix1 Values in matrix form
print("Matrix1 :")
for i in range(p):
    for j in range(n):
        print(format(Matrix1[i][j],"<5"),end=" ")
    print()

#Matrix 2
print("Enter the values for Matrix2")
Matrix2 = [[int(input()) for i in range(q)] for j in range(n)] 

# For printing the Matrix1 Values in matrix form
print("Matrix2 :")
for i in range(n):
    for j in range(q):
        print(format(Matrix2[i][j],"<5"),end=" ")
    print()

# Output

# Print the final added values of both matrices
print("Multiplied value of two matrices :")
result = []
result = np.dot(Matrix1,Matrix2)

for i in result:
    print(i)

Enter the row size for M1:2
Enter the column size for M2:2
Enter the column size for col_M1/row_M2:3
Enter the values for Matrix1
4
5
6
9
8
7
Matrix1 :
4     5     6     
9     8     7     
Enter the values for Matrix2
4
5
6
3
2
1
Matrix2 :
4     5     
6     3     
2     1     
Multiplied value of two matrices :
[58 41]
[98 76]


In [4]:
# Q4 Adding and Subtracting Matrices in Python

# Addition using numpy
# Matrix 1
A=[ [11, 25, 32], [30, 14, 15], [6, 27, 8] ]

# Matrix 2
B=[ [5, 16, 37], [10, 29, 33], [15, 34, 18] ]

print("Result M1 + M2: ")
print(np.add(A,B))

# Subtraction using numpy
# Matrix 1
A=[ [11, 25, 32], [30, 14, 15], [6, 27, 8] ]

# Matrix 2
B=[ [5, 16, 37], [10, 29, 33], [15, 34, 18] ]

print("Result M1 - M2: ")
print(np.subtract(A,B))

Result M1 + M2: 
[[16 41 69]
 [40 43 48]
 [21 61 26]]
Result M1 - M2: 
[[  6   9  -5]
 [ 20 -15 -18]
 [ -9  -7 -10]]


In [5]:
# Q5 Transpose a matrix in Single line in Python

# Input
row  = int(input("Enter the row size :"))
column = int(input("Enter the column size :"))

print("Enter the values for Matrix1")
# Matrix 1
Matrix1 = [[int(input()) for i in range(column)] for j in range(row)] 

print("Matrix :")
for i in range(row):
    for j in range(column):
        print(format(Matrix1[i][j],"<5"),end=" ")
    print()
    
# Transpose
result = [[0 for i in range(row)] for j in range(column)]

# Output

for i in range(column):
    for j in range(row):
        result[i][j] = Matrix1[j][i]

print("Transposed Matrix :")
for i in range(column):
    for j in range(row):
        print(format(result[i][j],"<5"),end=" ")
    print()

Enter the row size :3
Enter the column size :3
Enter the values for Matrix1
9
6
3
3
5
7
9
5
1
Matrix :
9     6     3     
3     5     7     
9     5     1     
Transposed Matrix :
9     3     9     
6     5     5     
3     7     1     


In [6]:
# Q6 Python | Matrix creation of n * n 

# input
n = 4
# creating list using list comprehension method
matrix = [list(range(1 + n * i, 1 + n * (i + 1))) for i in range(n)]
# output
print("The created matrix of {} * {}: ".format(n,n))
for m in matrix:
    print(m)

The created matrix of 4 * 4: 
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


In [7]:
# Q7 Python | Get Kth Column of Matrix

# Matrix

x = [[1,2,3],[4,5,6],[7,8,9]]

# create function

def find_column(k):
    col = [i[k] for i in x]
    print("The kth column in matrix is ",col)
    
find_column(2)

The kth column in matrix is  [3, 6, 9]


In [8]:
# Q8 Python – Vertical Concatenation in Matrix

# Input
x = [['We ',' to '],[' are ',' movie '],[' going ',' today.']]

# Using loop

lis = []
n = 0
while n != len(x):
    temp = ''
    for i in x:
        # check for valid index/column
        try: temp = temp + i[n]
        except IndexError: pass
    lis.append(temp)
    n = n+1

# Outputx`
lis = [ l for l in lis if l]

print("List after column concatenation : ",lis)

List after column concatenation :  ['We  are  going ', ' to  movie  today.']


In [9]:
# Q9 Python program to check if a string is palindrome or not

my_string=input("Enter string:")
if(my_string==my_string[::-1]):
   print("The string is a palindrome")
else:
   print("The string isn't a palindrome")

Enter string:malayalam
The string is a palindrome


In [10]:
# Q10 Python program to check whether the string is Symmetrical or Palindrome

def palin(string): 
  # declare and initialize with the starting and ending indexes
  st = 0
  end = len(string)-1
  f = 0
  # loop comparing letters moving from start to end and from end to start
  while(st<end): 
    if (string[st]== string[end]): 
      
      st += 1
      end -= 1
      
    else: 
      f = 1
      break; 
  # if loop with f as condition    
  if f == 0: 
    print("The entered string is palindrome") 
  else: 
    print("The entered string is not palindrome") 
    
# symm function to check string symmetrical or not
def symm(string): 
  
  l = len(string) 
  flag = 0
  
  # to check length of string even or odd 
  # to calculate middle value accordingly
  if l%2 == 0: 
    mid = l//2 # for even length
  else: 
    mid = l//2 + 1 # for odd length
    
  s1 = 0  # starting for first portion of string
  s2 = mid # starting for rest portion of string after middle value
  
  while(s1 < mid and s2 < l): 
    
    if (string[s1] == string[s2]): # comparing from start of both portions 
                                  # of given string
      s1 = s1 + 1
      s2 = s2 + 1
    else: 
      flag = 1
      break
  
  if flag == 0: 
    print("The entered string is symmetrical") 
  else: 
    print("The entered string is not symmetrical") 
    
# Main code 
string = input("Enter the string: ")
palin(string) 
symm(string)

Enter the string: momo
The entered string is not palindrome
The entered string is symmetrical
